version: '2'
services:
  jhipster_app-mongodb:
    image: mongo:4.0.10
    ports:
      - '27017:27017'
    command: mongos --configdb jhipster_app-mongodb-config
  jhipster_app-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  jhipster_app-mongodb-config:
    image: mongo:4.0.10
    container_name: jhipster_app-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
